version: '3.8'

services:
  alligator:
    image: openjdk:21
    ports:
      - "8080:8080"
    volumes:
      - ../AlligatorApi/target:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: java --enable-preview -jar AlligatorApplication.jar
    depends_on:
      - db
    networks:
      - internal
    restart: always

  db:
    image: postgres:latest
    ports:
      - "8001:5432"
    environment:
      POSTGRES_DB: alligator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge
