server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/alligator
    username: postgres
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: PostgreSQLDialect

  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.metrics.mongo.MongoMetricsAutoConfiguration


jwt:
  secret: 'lolkek'